services:
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - "./loki-config.yml:/etc/loki/loki-config.yml"

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - "./promtail-config.yml:/etc/promtail/promtail-config.yml"
      - "../../microservices/auth/tests/test-config/logs/auth-service.log:/var/log/auth-service.log"
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    ports:
      - "3000:3000"
    volumes:
      - "./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
    depends_on:
      - loki
